package com.rootscare.serviceprovider.ui.hospital.hospitalpaymenttransaction

import com.rootscare.serviceprovider.ui.base.BaseViewModel
import com.rootscare.serviceprovider.ui.hospital.hospitalsamplecollection.FragmentHospitalSampleCollectionNavigator

class FragmentHospitalPaymentTransactionViewModel  : BaseViewModel<FragmentHospitalPaymentTransactionNavigator>(){
}