package com.rootscare.serviceprovider.ui.physiotherapy.appointmentlist

import com.rootscare.serviceprovider.ui.base.BaseViewModel
import com.rootscare.serviceprovider.ui.labtechnician.labtechnicianmyappointment.FragmentLabtechnicianMyAppointmentNavigator

class FragmentPhysiotherapyAppointmentListViewModel : BaseViewModel<FragmentPhysiotherapyAppointmentListNavigator>() {
}