package com.rootscare.serviceprovider.ui.doctor.doctormyschedule.subfragment.adddoctorscheduletime

import com.rootscare.serviceprovider.ui.base.BaseViewModel
import com.rootscare.serviceprovider.ui.doctor.doctormyschedule.subfragment.FragmentdoctorManageScheduleNavigator

class FragmentAddDoctorScheduleTimeViewModel: BaseViewModel<FragmentAddDoctorScheduleTimeNavigator>() {
}