package com.rootscare.serviceprovider.ui.hospital.hospitaluploadpathologyreport

import com.rootscare.serviceprovider.ui.base.BaseViewModel
import com.rootscare.serviceprovider.ui.hospital.hospitalsamplecollection.FragmentHospitalSampleCollectionNavigator

class FragmentHospitalUploadPathologyReportViewModel : BaseViewModel<FragmentHospitalUploadPathologyReportNavigator>() {
}