package com.rootscare.serviceprovider.ui.hospital.hospitalmanageappointments

import com.rootscare.serviceprovider.ui.base.BaseViewModel
import com.rootscare.serviceprovider.ui.hospital.hospitalmanagedoctor.FragmenthospitalManageDoctorNavigator

class FragmentHospitalManageAppointmentsViewModel : BaseViewModel<FragmentHospitalManageAppointmentsNavigator>() {
}